{{- range $name, $_ := .Values.services }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aegis.fullname" $ }}-{{ $name }}
  labels:
    {{- include "aegis.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
automountServiceAccountToken: false
{{- end }}
